org: lezzito
app: serveless
service: serverless-framework-2-lambda
frameworkVersion: '4'

resources:
  extensions:
    S3BucketAlunoscsv:
      Properties:
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
              AllowedOrigins:
                - '*'

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:GetObject'
          Resource:
            - 'arn:aws:s3:::alunos-csv/*'

functions:
  cadastrarAluno:
  handler: cadastro_batch/aws/handler.cadastrarAluno
  events:
    - s3:
        bucket: alunos-csv
        event: s3:ObjectCreated:*
        rules:
          - suffix: .csv

  simulandoUploadDoCsv:
    handler: cadastro_batch/local/handler.simulandoUploadDoCsv
    events:
      - httpApi:
          path: /alunos/batch
          method: post
    enabled: false

  cadastrarAlunoNoBucketLocal:
    handler: cadastro_batch/local/handler.cadastrarAlunoNoBucketLocal
    events:
      - s3:
          bucket: alunos-csv-local
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv
    enabled: false

plugins:
  - serverless-s3-local
  - serverless-offline
  - serverless-disable-functions
